### ISSUE TITLE
textures bug out and become seethrough

### ISSUE THREAD

**Issue by KingOfStrangeness69** [steves-underwater-paradise/blinkload#6] opened 2024-09-05 18:38 UTC
![image](https://github.com/user-attachments/assets/ca914487-df09-4164-802f-82188b1b1965)
basically what the title says

**Comment by Steveplays28** [comment] 2024-09-05 18:46
Duplicate of #5. Sorry about this issue, I've not yet found out why it happens.

**Closed as not planned by Steveplays28** 2024-09-05 18:46 UTC
Labels: bug, duplicate

**Comment by Steveplays28** [comment] 2024-09-08 19:30
Fixed in [`v1.1.0`](https://github.com/steves-underwater-paradise/blinkload/releases/latest).
